###
GET http://localhost:8080/

###
GET http://localhost:8080/people

### Alle custom queries abfragen
GET http://localhost:8080/people/search

###
GET http://localhost:8080/people/?size=2

###
GET http://localhost:8080/people/?page=0&size=2

###
GET http://localhost:8080/people/search/findByFirstName?firstName=Hans

### page size 5 > navigation first, next, last
GET http://localhost:8080/people/search/lastNameStartsWith?lastName=Mei&page=0&size=2

### sorting
GET http://localhost:8080/people/search/lastNameStartsWith?lastName=Mei&sort=firstName,desc

###
GET http://localhost:8080/people/5

###
PUT http://localhost:8080/people/5
Content-Type: application/json

{
	"firstName": "Hans",
	"lastName": "Vier",
	"birthday": "1980-01-01",
	"kundenportalBenutzer": {
		"vorname": "KunVorname",
		"nachname": "KunNachname",
		"geschlecht": "maennlich",
		"sprache": "englisch"
	},
	"addressList": [
		{
			"addressType": "privat",
			"street": "Luzernstrasse 85"
		}
	],
	"communicationList": [
		{
			"type": "web",
			"content": "www.facebook.com/45699999"
		}
	]
}

###
PATCH http://localhost:8080/people/5
Content-Type: application/json

{
	"firstName": "Hans-Ueli",
	"addressList": [
		{
			"addressType": "geschaeft",
			"street": "Luzernstrasse 1"
		}
	]
}

###
POST http://localhost:8080/people
Content-Type: application/json

{
	"firstName": "Neu",
	"lastName": "Inserto",
	"birthday": "1960-01-01",
	"kundenportalBenutzer": {
		"vorname": "Rudi",
		"nachname": "Rüssel",
		"geschlecht": "maennlich",
		"sprache": "deutsch"
	}
}

###
GET http://localhost:8080/people/search/findByFirstName?firstName=Neu

### TODO does not work!?!
DELETE http://localhost:8080/people/search/deleteByFirstName?firstName=Neu

### with relations
POST http://localhost:8080/people
Content-Type: application/json

{
	"firstName": "Neuer",
	"lastName": "Creator",
	"birthday": "1980-01-01",
	"kundenportalBenutzer": {
		"vorname": "Hansi",
		"nachname": "Hinterseher",
		"geschlecht": "maennlich",
		"sprache": "deutsch"
	},
	"addressList": [
		{
			"addressType": "geschaeft",
			"street": "Zentralstrasse 2a"
		}
	],
	"communicationList": [
		{
			"type": "web",
			"content": "www.suva.ch/"
		}
	]
}

### EventHandler
DELETE http://localhost:8080/people/17

### exception handling
POST http://localhost:8080/people
Content-Type: application/json

{
	"firstName": "Neu",
	"lastName": "Inserto",
	"birthday": "GAGA",
	"kundenportalBenutzer": {
		"vorname": "Rudi",
		"nachname": "Rüssel",
		"geschlecht": "GAGA",
		"sprache": "GAGA"
	}
}

